[[main]]
  name = "Event"
  pre = 'ğŸ²'
  weight ='2'
  url = "/event"

[[main]]
  name = "PembaTIK 2024"
  pre = '<img src="https://pembatik.kemdikbud.go.id/wp-content/uploads/2024/05/icon-pembatik-150x150.png" class="ml-2 w-4 h-4">'
  weight ='3'
  url = "https://pembatik.kemdikbud.go.id"
[[main]]
  name = "Tutorial"
  pre = 'ğŸ–Œï¸'
  weight ='3'
  url = "/tutorial"

[[footer]]
  name = "About"
  url = "/about"
  weight = 1

[[footer]]
  name = "Contact"
  url = "/contact"
  weight = 2
[[footer]]
  name = "Archive"
  url = "/arsip"
  weight = 3
[[footer]]
  name = "Kebijakan Privasi"
  url = "/privacy-police"
  weight = 4
